### ISSUE TITLE
Iridium transmission

### ISSUE THREAD

**Issue by jvoermans** [jerabaul29/LoggerWavesInIce_InSituWithIridium#7]
@jerabaul29 
is the RPi or the Arduino responsible for the final transmission of data? i.e. if I want to send temperature through Iridium as well, perhaps easiest to do with the GPS data transmission, what files should I start?

Is that in the 'IridiumManager.cpp' file?

**Comment by jerabaul29** [comment]
The Arduino is responsible. Yes, it is this file. I let you look at the code to get started. Basically, you need to 1) write the day in the TX buffer of the Iridium 2) ask to send.

**Comment by Eiserklaus** [comment]
Hi,

Hi, would this module be of any value for your research:
https://www.taoglas.com/product/edge-locate/

**Comment by jerabaul29** [comment]
Hi,

This could be of interest for measuring very low frequency waves, but I think the IMU is a bit better in our case (we manage to measure waves of a few mms, but this has a cm resolution only).
