### ISSUE TITLE
enhancement: add LCD display

### ISSUE THREAD

**Issue by jerabaul29** [jerabaul29/LoggerWavesInIce_InSituWithIridium#8]
Would be great to add LCD display, facultatory, for debug etc.

**Comment by Eiserklaus** [comment]
Hi Jean,

I am no longer working at Labmaker and my colleague Hendrik Joosten will further pursue this project. I have forwarded your suggestions to him and if you want to contact him his e-mail is Hendrik@labmaker.org
Thank you very much for your help and for designing this great tool

Klaus

**Comment by jerabaul29** [comment]
Hi,

Ok, good luck with your new position!

Best,

Jean
